kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: confdeploy
spec: 
  replicas: 1 
  selector:
    matchLabels: 
      class: cm  
  template: 
    metadata: 
      name: cmdp
      labels: 
        class: cm
    spec: 
      containers: 
        - name: cmcon 
          image: ubuntu 
          command: ["/bin/bash","-c","echo cmcon; sleep 4893"]
          env: 
            - name: configMap 
              valueFrom: 
                configMapKeyRef: 
                  name: cm
                  key: configMap.conf 
            - name: secret
              valueFrom: 
                secretKeyRef:
                  name: secret 
                  key: secrets.conf 
          volumeMounts: 
            - name: cmvol 
              mountPath: /cmvolume
            - name: secvol
              mountPath: /secvolume 
      volumes: 
        - name: cmvol 
          configMap: 
            name: cm 
            items: 
              - key: configMap.conf
                path: configMap.conf
        - name: secvol
          secret:
            secretName: secret

            
