kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: crondeploy 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      class: initdp 
  template: 
    metadata: 
      name: initPod
      labels:  
        class: initdp 
    spec: 
      initContainers:
        - name: init 
          image: ubuntu 
          command: ["/bin/bash","-c","echo init container; sleep 10"]
      containers: 
        - name: initcon 
          image: centos
          args: 
            - "/bin/bash"
            - "-c"
            - "echo main container; sleep 86590"
            
--- 
kind: Job 
apiVersion: batch/v1 
metadata: 
  name: job
spec: 
  template: 
    metadata:  
      name: jobpod
      labels: 
        class: job  
    spec: 
      containers:  
        - name: jobcon 
          image: ubuntu 
          args: 
            - "/bin/bash"
            - "-c"
            - "echo job pod ; sleep 10" 
      restartPolicy: Never 

--- 
kind: CronJob 
apiVersion: batch/v1
metadata: 
  name: cronjob
spec:
  schedule: "* * * * */5"
  jobTemplate: 
    spec:
      template:   
        spec:
          containers:   
            - name: cronpod 
              image: ubuntu 
              args: 
                - /bin/bash
                - -c 
                - echo cronjob; sleep 10
          restartPolicy: Never 

  