---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: svcdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      class: svcdeploy
  template:
    metadata:
      name: svcpod
      labels:
        class: svcdeploy
        env: svc
    spec:
      containers:
        - name: svccon
          image: nginx
          ports:
            - containerPort: 80
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    env: svc
  type: NodePort


